// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PersonalAccount.Data;

#nullable disable

namespace PersonalAccount.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("PersonalAccount.Data.Entities.AccountEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("password_hash");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("PersonalAccount.Data.Entities.ConfirmationTokenEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("account_id");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("confirmed_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("expires_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("token_hash");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("confirmation_tokens", (string)null);
                });

            modelBuilder.Entity("PersonalAccount.Data.Entities.GroupEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2047)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2047)
                        .HasColumnType("TEXT")
                        .HasColumnName("photo_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("groups", (string)null);
                });

            modelBuilder.Entity("PersonalAccount.Data.Entities.StudentProfileEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("account_id");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("full_name");

                    b.Property<int?>("GroupId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("group_id");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(2047)
                        .HasColumnType("TEXT")
                        .HasColumnName("photo_url");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.HasIndex("GroupId");

                    b.ToTable("student_profiles", (string)null);
                });

            modelBuilder.Entity("PersonalAccount.Data.Entities.SubjectEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("subjects", (string)null);
                });

            modelBuilder.Entity("PersonalAccount.Data.Entities.TeacherGroupSubjetEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("GroupId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("group_id");

                    b.Property<int>("SubjectId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("subject_id");

                    b.Property<int>("TeacherAccountId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("teacher_account_id");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherAccountId");

                    b.ToTable("teacher_group_subjets", (string)null);
                });

            modelBuilder.Entity("PersonalAccount.Data.Entities.TeacherProfileEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("account_id");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("full_name");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(2047)
                        .HasColumnType("TEXT")
                        .HasColumnName("photo_url");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.ToTable("teacher_profiles", (string)null);
                });

            modelBuilder.Entity("PersonalAccount.Data.Entities.ConfirmationTokenEntity", b =>
                {
                    b.HasOne("PersonalAccount.Data.Entities.AccountEntity", "Account")
                        .WithMany("ConfirmationTokens")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("PersonalAccount.Data.Entities.StudentProfileEntity", b =>
                {
                    b.HasOne("PersonalAccount.Data.Entities.AccountEntity", "Account")
                        .WithOne("StudentProfile")
                        .HasForeignKey("PersonalAccount.Data.Entities.StudentProfileEntity", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PersonalAccount.Data.Entities.GroupEntity", "Group")
                        .WithMany("StudentProfiles")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Account");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("PersonalAccount.Data.Entities.TeacherGroupSubjetEntity", b =>
                {
                    b.HasOne("PersonalAccount.Data.Entities.GroupEntity", "Group")
                        .WithMany("TeacherGroupSubjets")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PersonalAccount.Data.Entities.SubjectEntity", "Subject")
                        .WithMany("TeacherGroupSubjets")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PersonalAccount.Data.Entities.AccountEntity", "TeacherAccount")
                        .WithMany("TeacherGroupSubjets")
                        .HasForeignKey("TeacherAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Subject");

                    b.Navigation("TeacherAccount");
                });

            modelBuilder.Entity("PersonalAccount.Data.Entities.TeacherProfileEntity", b =>
                {
                    b.HasOne("PersonalAccount.Data.Entities.AccountEntity", "Account")
                        .WithOne("TeacherProfile")
                        .HasForeignKey("PersonalAccount.Data.Entities.TeacherProfileEntity", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("PersonalAccount.Data.Entities.AccountEntity", b =>
                {
                    b.Navigation("ConfirmationTokens");

                    b.Navigation("StudentProfile");

                    b.Navigation("TeacherGroupSubjets");

                    b.Navigation("TeacherProfile");
                });

            modelBuilder.Entity("PersonalAccount.Data.Entities.GroupEntity", b =>
                {
                    b.Navigation("StudentProfiles");

                    b.Navigation("TeacherGroupSubjets");
                });

            modelBuilder.Entity("PersonalAccount.Data.Entities.SubjectEntity", b =>
                {
                    b.Navigation("TeacherGroupSubjets");
                });
#pragma warning restore 612, 618
        }
    }
}
